### ISSUE TITLE
DB setup doesn't respect db-creds.inc's dbname preferences

### ISSUE THREAD

**Issue by lurodrigo** [Audi-1/sqli-labs#1]
DB setup/reset always create a database with name 'security' instead of using the dbname we put in db-creds.inc. Not much of a problem, though.

**Comment by Audi-1** [comment]
It was not made with that intent, the DB setup/reset was scribbled for plug and play for people who are very new to databases, or for a quick cleaning of DB to default values. I would fix this in near future, thanks for  bringing it up.
