### ISSUE TITLE
Not working on php7

### ISSUE THREAD

**Issue by charaneadam** [Audi-1/sqli-labs#10]
mysql_\* functions not working on php7

**Comment by Audi-1** [comment]
Yes, Mysql_* functions are depreciated and now PHP uses mysqli_* functions which support stacking of queries apart from other improvements. You can work with XAMPP or XAMPPLite to test and build lab on it.

**Comment by sandroded** [comment]
I had the same issue on Kali 2016.2. (PHP 7)
Now I am using docker container: tuxotron/audi_sqli and it works well

**Comment by charaneadam** [comment]
I taught in that solution (dockerize apache with php5) but I installed an
older of php instead
Thanks anyway !! 😀😀
