### ISSUE TITLE
problem with lesson 2

### ISSUE THREAD

**Issue by ghost** [Audi-1/sqli-labs#2]
Hello, 

I understand that with ?=id=1' you can break the query.
But in your videos I cannot find how to repair it. I only see lesson 1 , 3 and 4 

Roelof

**Comment by Audi-1** [comment]
Hi @roelof1967 
This is not an issue with the labs sources, I left that part in videos deliberately. If you watch again video 2-5 and try to understand the core concepts explained, you will be able to figure out issue, else please write to me at auditor.sec[at]gmail[dot]com.
