### ISSUE TITLE
lesson 4 is not working as expected

### ISSUE THREAD

**Issue by ghost** [Audi-1/sqli-labs#3]
Hello, 

On lessons 4 when I do http://localhost/sqli-labs/Less-4/?id=1'   I don't get a error message 

Roelof

**Comment by Audi-1** [comment]
hi @roelof1967 
This is not a bug with lab, but it is intended this way. you can see the brief description on the main page about the core logic of that lesson. Less-4 mentions it to be error based double quotes, means you would need double quotes to get the error.
