### ISSUE TITLE
problem with index.html_files/image.png

### ISSUE THREAD

**Issue by lyenliang** [Audi-1/sqli-labs#4]
I found that this image does not match the contents of the lessons. 
For example:
The query in lesson 4 is $sql="SELECT \* FROM users WHERE id=($id) LIMIT 0,1";, which uses round brackets, but image.png says double quotes are used in lesson 4. 

Is image.png not correct? Or do I misinterpret the meanings of the words in image.png?

**Comment by Audi-1** [comment]
I guess there is some confusion over the page. If you look closely few lines above, You would observe that double quotes are being concatenated to input string and this concatenated input is being added to the query which caused your confusion.  Hope this clears it.
