### ISSUE TITLE
i have an issue on audi sqli labs basic level one ,i have inserted (id=1) (ID=1) parameter with value and  i shows 404 error 

### ISSUE THREAD

**Issue by vineeth9100** [Audi-1/sqli-labs#52]
![Screenshot_2022-04-29_level one ](https://user-images.githubusercontent.com/104612538/165888102-b8751ccf-b114-42d0-99dc-09c268b6bc77.png)

**Comment by Audi-1** [comment]
From screenshot it is seen that you are entering parameters with a / which is incorrect. you should enter it with ?. Example http://localhost/sqlilabs/Less-1/?ID=1
