### ISSUE TITLE
Firewall lesson 29

### ISSUE THREAD

**Issue by prvnkumark** [Audi-1/sqli-labs#6]
Hi Audi,

I have been following your awesome sqli labs, i am stuck with tomcat firewall lab. I am getting below error. I can confirm  sample lesson 32 works fine with apache tomcat.

type Exception report

message An exception occurred processing JSP page /sqli-labs/Less-29/index.jsp at line 61

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.io.IOException: An exception occurred processing JSP page /sqli-labs/Less-29/index.jsp at line 61

58:         URLConnection sqli_labs_connection = sqli_labs.openConnection();
59:         BufferedReader in = new BufferedReader(
60:                                 new InputStreamReader(
61:                                 sqli_labs_connection.getInputStream()));
62:         String inputLine;
63:         while ((inputLine = in.readLine()) != null) 
64:             out.print(inputLine);

Stacktrace:
    org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:467)
    org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

root cause

java.io.FileNotFoundException: http://localhost/sqli-labs/Less-29/index.php
    sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
    org.apache.jsp.sqli_002dlabs.Less_002d29.index_jsp._jspService(index_jsp.java:124)
    org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
    org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
    org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.64 logs.

**Comment by Audi-1** [comment]
As discussed with you, it was caused due to your local environment and not because of some issue with labs

**Comment by ajaikumarnadar** [comment]
Hello Audi, this is Ajaikumar really like your Sqli-labs series and i am currently practicing it.. Thank you So much for your detailed tutorials.
Any plans for XSS tutorials.. ?
I would like to learn XSS in detailed way...
