### ISSUE TITLE
Please include solutions too, in case a person failed to inject

### ISSUE THREAD

**Issue by Multi-Thinker** [Audi-1/sqli-labs#9]
Please Include solutions at the end if a person fails to inject, i'm having real hard time figuring out and SQL injection is the only thing i can't find any guide about, it is hard to learn and no where to found.. Please add solutions too so i can learn from it.

**Comment by 007divyachawla** [comment]
http://dummy2dummies.blogspot.com
http://www.securitytube.net/user/Audi
https://www.facebook.com/sqlilabs

Please watch this links for the solutions

**Comment by Audi-1** [comment]
Thanks 007divyachawla for informing about the leads.
